//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现方法。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-06-28 14:37
// </copyright>
//------------------------------------------------------------------------------
using ApartmentRent.IDAL;

namespace ApartmentRent.DAL
{
    /// <summary>
    /// 实体类-数据表映射——ActualAmountDetail
    /// </summary>  
	public partial class ActualAmountDetailDal : BaseDal, IActualAmountDetailDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BillRent
    /// </summary>  
	public partial class BillRentDal : BaseDal, IBillRentDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Building
    /// </summary>  
	public partial class BuildingDal : BaseDal, IBuildingDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BuildRoom
    /// </summary>  
	public partial class BuildRoomDal : BaseDal, IBuildRoomDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseOwner
    /// </summary>  
	public partial class HouseOwnerDal : BaseDal, IHouseOwnerDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseRenter
    /// </summary>  
	public partial class HouseRenterDal : BaseDal, IHouseRenterDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——PayTypeInfo
    /// </summary>  
	public partial class PayTypeInfoDal : BaseDal, IPayTypeInfoDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RentRecords
    /// </summary>  
	public partial class RentRecordsDal : BaseDal, IRentRecordsDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Things
    /// </summary>  
	public partial class ThingsDal : BaseDal, IThingsDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WaterPowerRent
    /// </summary>  
	public partial class WaterPowerRentDal : BaseDal, IWaterPowerRentDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WeChatUserInfo
    /// </summary>  
	public partial class WeChatUserInfoDal : BaseDal, IWeChatUserInfoDal
	{
	}

}