//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类实现方法。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-07-01 15:35
// </copyright>
//------------------------------------------------------------------------------
using ApartmentRent.IBLL;
using ApartmentRent.IDAL;

namespace ApartmentRent.BLL
{
    /// <summary>
    /// 实体类-数据表映射——ActualAmountDetail
    /// </summary>  
	public partial class ActualAmountDetailService : BaseService<IActualAmountDetailDal>, IActualAmountDetailService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BillRent
    /// </summary>  
	public partial class BillRentService : BaseService<IBillRentDal>, IBillRentService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Building
    /// </summary>  
	public partial class BuildingService : BaseService<IBuildingDal>, IBuildingService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BuildRoom
    /// </summary>  
	public partial class BuildRoomService : BaseService<IBuildRoomDal>, IBuildRoomService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseOwner
    /// </summary>  
	public partial class HouseOwnerService : BaseService<IHouseOwnerDal>, IHouseOwnerService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseRenter
    /// </summary>  
	public partial class HouseRenterService : BaseService<IHouseRenterDal>, IHouseRenterService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——PayTypeInfo
    /// </summary>  
	public partial class PayTypeInfoService : BaseService<IPayTypeInfoDal>, IPayTypeInfoService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RentRecords
    /// </summary>  
	public partial class RentRecordsService : BaseService<IRentRecordsDal>, IRentRecordsService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Things
    /// </summary>  
	public partial class ThingsService : BaseService<IThingsDal>, IThingsService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WaterPowerRent
    /// </summary>  
	public partial class WaterPowerRentService : BaseService<IWaterPowerRentDal>, IWaterPowerRentService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WeChatUserInfo
    /// </summary>  
	public partial class WeChatUserInfoService : BaseService<IWeChatUserInfoDal>, IWeChatUserInfoService
	{
	}

}