//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类定义接口。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-06-28 14:34:23
// </copyright>
//------------------------------------------------------------------------------

namespace ApartmentRent.IDAL
{
    /// <summary>
    /// 实体类-数据表映射——ActualAmountDetail
    /// </summary>  
    public partial interface IActualAmountDetailDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BillRent
    /// </summary>  
    public partial interface IBillRentDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Building
    /// </summary>  
    public partial interface IBuildingDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BuildRoom
    /// </summary>  
    public partial interface IBuildRoomDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseOwner
    /// </summary>  
    public partial interface IHouseOwnerDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseRenter
    /// </summary>  
    public partial interface IHouseRenterDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——PayTypeInfo
    /// </summary>  
    public partial interface IPayTypeInfoDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RentRecords
    /// </summary>  
    public partial interface IRentRecordsDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Things
    /// </summary>  
    public partial interface IThingsDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WaterPowerRent
    /// </summary>  
    public partial interface IWaterPowerRentDal : IBaseDal
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WeChatUserInfo
    /// </summary>  
    public partial interface IWeChatUserInfoDal : IBaseDal
	{
	}

}