//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类定义接口。
// </auto-generated>
//
// <copyright file="WebSiteDbContext">
//		Copyright(c)2018 rights reserved.
//		开 发 者：黄翔宇@中国
//		生成时间：2018-06-30 00:57
// </copyright>
//------------------------------------------------------------------------------

namespace ApartmentRent.IBLL
{
    /// <summary>
    /// 实体类-数据表映射——ActualAmountDetail
    /// </summary>  
	public partial interface IActualAmountDetailService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BillRent
    /// </summary>  
	public partial interface IBillRentService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Building
    /// </summary>  
	public partial interface IBuildingService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——BuildRoom
    /// </summary>  
	public partial interface IBuildRoomService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseOwner
    /// </summary>  
	public partial interface IHouseOwnerService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——HouseRenter
    /// </summary>  
	public partial interface IHouseRenterService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——PayTypeInfo
    /// </summary>  
	public partial interface IPayTypeInfoService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——RentRecords
    /// </summary>  
	public partial interface IRentRecordsService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——Things
    /// </summary>  
	public partial interface IThingsService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WaterPowerRent
    /// </summary>  
	public partial interface IWaterPowerRentService : IBaseService
	{
	}

    /// <summary>
    /// 实体类-数据表映射——WeChatUserInfo
    /// </summary>  
	public partial interface IWeChatUserInfoService : IBaseService
	{
	}

}